"""Initial migration

Revision ID: 589a741f456e
Revises: 
Create Date: 2025-12-08 09:39:45.367988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589a741f456e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('chess_games',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('moves', sa.JSON(), nullable=False),
    sa.Column('move_analysis', sa.JSON(), nullable=True),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('white_player', sa.String(length=255), nullable=True),
    sa.Column('black_player', sa.String(length=255), nullable=True),
    sa.Column('white_elo', sa.Integer(), nullable=True),
    sa.Column('black_elo', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=255), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('game_date', sa.String(length=20), nullable=True),
    sa.Column('opening', sa.String(length=255), nullable=True),
    sa.Column('eco', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_curated', sa.Boolean(), nullable=False),
    sa.Column('commentary_status', sa.String(length=20), nullable=True),
    sa.Column('commentary_generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chess_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chess_games_game_type'), ['game_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_chess_games_is_curated'), ['is_curated'], unique=False)
        batch_op.create_index(batch_op.f('ix_chess_games_user_id'), ['user_id'], unique=False)

    op.create_table('live_game_states',
    sa.Column('game_id', sa.String(length=100), nullable=False),
    sa.Column('lichess_game_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('player_color', sa.String(length=10), nullable=False),
    sa.Column('ai_level', sa.Integer(), nullable=False),
    sa.Column('current_fen', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['chess_games.id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    with op.batch_alter_table('live_game_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_game_states_lichess_game_id'), ['lichess_game_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_live_game_states_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_game_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_game_states_status'))
        batch_op.drop_index(batch_op.f('ix_live_game_states_lichess_game_id'))

    op.drop_table('live_game_states')
    with op.batch_alter_table('chess_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chess_games_user_id'))
        batch_op.drop_index(batch_op.f('ix_chess_games_is_curated'))
        batch_op.drop_index(batch_op.f('ix_chess_games_game_type'))

    op.drop_table('chess_games')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
