"""add version to live game state

Revision ID: c6b775c93346
Revises: fe2c0978f7fa
Create Date: 2025-12-12 10:12:05.988622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b775c93346'
down_revision = 'fe2c0978f7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_game_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_game_states', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
