"""add engine type

Revision ID: fe2c0978f7fa
Revises: 589a741f456e
Create Date: 2025-12-08 09:48:17.724032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2c0978f7fa'
down_revision = '589a741f456e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_game_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engine_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_game_states', schema=None) as batch_op:
        batch_op.drop_column('engine_type')

    # ### end Alembic commands ###
